spring:
  application:
    name: oauth2RegLgn
  security:
    user:
      name: abc
      password: 123
    oauth2:
      client:
        registration:
          google:
            client-id: 112209610000-mrllfev6c042aco8s5usr37rqinc4kb2.apps.googleusercontent.com
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
            redirect-uri: http://localhost:8080/user
          github:
            client-id: ${YOUR_GITHUB_CLIENT_ID}
            client-secret: YOUR_GITHUB_CLIENT_SECRET
            scope:
              - read:user
              - user:email
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: ${id}
